### ISSUE TITLE
how make input motion vector frame on B frame ?

### ISSUE THREAD

**Issue by zsz00** [casys-kaist/CoVA#2]
How make input motion vector frame on B frame ?
In B frame, every location (x1,y1) have tow (MVw, MVh), how to make a mv frame? 

location (x1,y1): (mv_x1, mv_y1, mv_x2, mv_y2)   ? 
or 
frame1: location (x1,y1): (mv_x1, mv_y1)    ? 
frame2: location (x1,y1): (mv_x2, mv_y2)

**Comment by jinuhwang** [comment]
Hi, I just used one of them (L1 motion vector) in this work, as they were good enough.
