### ISSUE TITLE
About compression metadata processing

### ISSUE THREAD

**Issue by censhallwe** [casys-kaist/CoVA#3]
Hi, I haven seen your paper and code. I am interested in compression metadata getting and processing.
![TX3GCIME7%~EJMG~6I4%~~A](https://user-images.githubusercontent.com/98868191/225261734-bfd49681-b32a-4684-a967-c29ef24b09fc.png)
In this picture, you get three compression metadata. For MB type and MB mode, I only find MB type in your code, so I wonder how you getting MB mode and processing them? And in where you combine them to an one-hot tensor? Could you please tell me the location of code about this?
Another question, you do an embedding operation. However, I also can't find it in your code, maybe I ingored it carelessly, so please tell me where it is.
Thank you very much! 고마워요❤

**Comment by jinuhwang** [comment]
Hi, sorry for the late response.

The MB mode in the paper is referring to the macroblock partitioning mode.
The `libavcodec` already uses bit vectors  to represent partitioning mode and macroblock type, so you would have to change it into one hot encoding.

**Comment by censhallwe** [comment]
> Hi, sorry for the late response.
> 
> The MB mode in the paper is referring to the macroblock partitioning mode. The `libavcodec` already uses bit vectors to represent partitioning mode and macroblock type, so you would have to change it into one hot encoding.

Thank you for your reply!🤝
Another question, where is the embedding operation in your code? Or you use other tools to process it? Please tell me🙏

**Comment by censhallwe** [comment]
> Hi, sorry for the late response.
> 
> The MB mode in the paper is referring to the macroblock partitioning mode. The `libavcodec` already uses bit vectors to represent partitioning mode and macroblock type, so you would have to change it into one hot encoding.

Hi, sorry to bother you again. Could you please tell me what the 12 macroblock type-mode combinations for H.264 they are? In the above image, you draw an one-hot vector with 18 values. And how do you do the embedding operation in your code?
Looking forward to your reply!

**Comment by censhallwe** [comment]
> Hi, sorry for the late response.
> 
> The MB mode in the paper is referring to the macroblock partitioning mode. The `libavcodec` already uses bit vectors to represent partitioning mode and macroblock type, so you would have to change it into one hot encoding.

Hi, sorry to bother you again. Could you please tell me what the 12 macroblock type-mode combinations for H.264 they are? In the above image, you draw an one-hot vector with 18 values. And how do you do the embedding operation in your code?
Looking forward to your reply!

**Comment by jinuhwang** [comment]
Apologies once more for the delayed reply.
The 12 combinations result from mixing 3 macroblock types with 4 carefully selected partitioning modes: 16x16, 16x8 (or 8x16), 8x8, and 4x4.
Such choice was made to prevent the model from becoming overly complicated, and we observed that it was effective for our blob detection stage.

**Comment by censhallwe** [comment]
> Apologies once more for the delayed reply. The 12 combinations result from mixing 3 macroblock types with 4 carefully selected partitioning modes: 16x16, 16x8 (or 8x16), 8x8, and 4x4. Such choice was made to prevent the model from becoming overly complicated, and we observed that it was effective for our blob detection stage.

Thank you for your reply! I got it!❤
